# Generated by Django 3.0.7 on 2020-06-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceparser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
