# Generated by Django 3.0.7 on 2020-07-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceparser', '0002_auto_20200616_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='ship_date',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='supplier',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceparser.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoiceparser.Invoice'),
            preserve_default=False,
        ),
    ]
