# Generated by Django 3.0.7 on 2020-08-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceparser', '0003_auto_20200809_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoiceparser.Supplier'),
            preserve_default=False,
        ),
    ]
